//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hylasoft.OrdersGui.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_en_us {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings_en_us() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hylasoft.OrdersGui.Resources.Strings_en-us", typeof(Strings_en_us).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier.
        /// </summary>
        public static string CarrierHeader {
            get {
                return ResourceManager.GetString("CarrierHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Manual Order.
        /// </summary>
        public static string CreateOrder {
            get {
                return ResourceManager.GetString("CreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string CustomerHeader {
            get {
                return ResourceManager.GetString("CustomerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Filter.
        /// </summary>
        public static string DateFilter {
            get {
                return ResourceManager.GetString("DateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Scheduled.
        /// </summary>
        public static string DateHeader {
            get {
                return ResourceManager.GetString("DateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Method.
        /// </summary>
        public static string DeliveryMethodHeader {
            get {
                return ResourceManager.GetString("DeliveryMethodHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTimeHeader {
            get {
                return ResourceManager.GetString("EndTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Order Manager.
        /// </summary>
        public static string LoadOrderManagerTitle {
            get {
                return ResourceManager.GetString("LoadOrderManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Orders: {0}.
        /// </summary>
        public static string NoOfOrders {
            get {
                return ResourceManager.GetString("NoOfOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC:.
        /// </summary>
        public static string OPCConnStatus {
            get {
                return ResourceManager.GetString("OPCConnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number:.
        /// </summary>
        public static string OrderNumberFilter {
            get {
                return ResourceManager.GetString("OrderNumberFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order No..
        /// </summary>
        public static string OrderNumberHeader {
            get {
                return ResourceManager.GetString("OrderNumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status Filter.
        /// </summary>
        public static string OrderStatusFilter {
            get {
                return ResourceManager.GetString("OrderStatusFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string OrderStatusHeader {
            get {
                return ResourceManager.GetString("OrderStatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Type.
        /// </summary>
        public static string OrderTypeHeader {
            get {
                return ResourceManager.GetString("OrderTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack.
        /// </summary>
        public static string RackHeader {
            get {
                return ResourceManager.GetString("RackHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Ref..
        /// </summary>
        public static string ShipRefHeader {
            get {
                return ResourceManager.GetString("ShipRefHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLOM Server:.
        /// </summary>
        public static string SLOMConnStatus {
            get {
                return ResourceManager.GetString("SLOMConnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTimeHeader {
            get {
                return ResourceManager.GetString("StartTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Scheduled.
        /// </summary>
        public static string TimeHeader {
            get {
                return ResourceManager.GetString("TimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: {0}.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
